language: node_js
node_js:
- '6'
sudo: false
branches:
  except:
  - gh-pages
before_script:
- npm install
- npm install -g jshint
- npm install -g mocha
script:
- jshint lib/countly.js
- mocha test/test-example.js
after_success:
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocs.sh
- bash generateDocs.sh
env:
  global:
    secure: J0ggNe9rS8VNwvj4Jb3MLnSvgjYBbjA++7aUFSjaqZLqhcl9cQv4UgmIMcc4Lhn5WnXJl5+beIYGQPmemTWTICJanM869YFXftJ6DitkYYBcm/9bcoKfQrWwHlQKGZe5V3Cs+LB28b19XdMUOGJwrnxKhlOCJDg+TIBI0wICeea+jZnF8ZndrKP451VTxuEEVD7B5HSpfBzxrpo9bwWbUOPP2xYrD6BuoBSDZ4Cdf+L3pcZih33auYg+vsViZbqSoj3slJVTdP9194hLlqTMqbnATtdStO9fT43cZK9FX4O5gEcbbncpjPuzcXQl9pSgbYRfC2c4rBWdo8DHIhou9ZVkmfTEyABWEiN4A+4KJ8ck547NAFKyewrtrvPDHO1garHDOtIHmBdTX8d0uGZQqwYhiB8UQKG3scmjZWUn3ptiKkzON4OzMOdtHTmSmDNo4xFZULcwoYR1xkbBGKWYPcnGby/4uUHnG3VuHg9AMZHhFjWYln59ga8M0Q2WofyWMv73LLPrSjnesEk2fau+xUnEtKRE0ogwdee3gux9OC/Q3UGc8Bdt157c0QHese482AY0nyQJCg0GsWBTfDVzYqcCJqdoY+2L2wHobdmOJOxJY619HZ1rFCReU+hi57YqoUebpWcfucbR3vRbVsw0SzUF4dQ50Dhpm9HYtwAw5zM=
notifications:
  slack:
    secure: VwgRLVLOuFlk4CtNugxUfR158e+4v+tbEzwhMLOEVJRgO9AEy7HvVelDYJmdZAcUGB/uuEvthQdwwWf4dUiOfHKdPiz42lSPNeMNpEMK9wKlekbsVrE2KrZv5jadPdFoVpnd7T5RZIxe8+ebTIWKwbDAQl/B8mTCF1kpFx1H+3SeZmAoPkR0bmcVqQFgGDwICzH3r0SjMTVzT71G0GZ67W/P1tnlx3J0wX/puzzO32x6KO9rJR6kiP+nGa0V49GpZ+Bsp9M0pfh9ZOCBu6D/INIJOzHWtJ0h0bWUk8RLVIlMtoVeJwYVdcQJFwgilxbTdCE+wKiqBe/tIz9+LTqetINymkHJzltr3hiIiWba2Kdsu2H4foFca+AtXhQ0kryl+GcOzfaoLIBVD8q8sMtIeTCk5rLgpXZG6Y9krC8IeYkil5+li9D10ZzOo2By1e/03apaf2Hy5FI9arXA6bq/vMIi1cyIgDAolPmV8BloGaKdb3Tb3RiVWx2oCAn3BiQcgyK+czfopjZGeysJPCtdpvkWYonm3/vDQsD440Dy83pJaQ5H9ii3qf2ldan4R2xzo44wi+fffAzRZkiQH+mWqlbhWa9+qybl5lfa9WKVAVB6k4x/XkZQOdzrUMeS4sESWmFS8h3qzv2z78DyjfhkghOP651y02xQ2yfTujgE4lc=
